<a href="https://colab.research.google.com/github/danish123-a/Question-Answer_Prediction_With-_Gradio/blob/main/Ques%20%26%20Ans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd


In [5]:
v=pd.read_csv("/content/100_Unique_Ques & Ans_Dataset.csv")

In [6]:
v

question        answer
0                      What is the capital of France?         Paris
1                     What is the capital of Germany?        Berlin
2                  Who wrote 'To Kill a Mockingbird'?    Harper-Lee
3     What is the largest planet in our solar system?       Jupiter
4      What is the boiling point of water in Celsius?           100
..                                                ...           ...
85                  Who directed the movie 'Titanic'?  JamesCameron
86  Which superhero is also known as the Dark Knight?        Batman
87                     What is the capital of Brazil?      Brasilia
88        Which fruit is known as the king of fruits?         Mango
89       Which country is known for the Eiffel Tower?        France

[90 rows x 2 columns]

In [7]:
#seprate word by split fun

In [8]:
def tokenize_(text):
  text=text.lower()
  text=text.replace("?","")
  text=text.replace("'","")
  return text.split()

In [9]:
tokenize_("Which country is known for the Eiffel Tower?	")

['which', 'country', 'is', 'known', 'for', 'the', 'eiffel', 'tower']

In [10]:
#make a vocabolury
vocabulary={"I don't know":0}

In [11]:
def vocab(row):
  #print(row["question"],row["answer"])
  question_token=tokenize_(row["question"])
  answer_token=tokenize_(row["answer"])
  words=question_token+answer_token
  #print(words)
  for word in words:
    #print(word)
    if word not in vocabulary:
      vocabulary[word]=len(vocabulary)




In [12]:
v.apply(vocab,axis=1)

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [13]:
vocabulary

{"I don't know": 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,

In [14]:
#legth of vocabulary
len(vocabulary)

324

In [15]:
#now we access the indicess of each words present in vocabulary


In [16]:
def text_to_indicess(text,vocabulary):
  indicess_values=[]
  text=tokenize_(text)
  dic=vocabulary
  for i in text :
    if i in dic:
      indicess_values.append(dic[i])
    else:
      indicess_values.append(dic["I don't know"])
  return indicess_values


In [17]:
print(text_to_indicess("Which is my",vocabulary))

[42, 2, 0]


In [18]:
import torch as t

In [19]:
from torch.utils.data import Dataset,DataLoader

In [20]:
#now we make a DataLoader class
class Ques_Ans(Dataset):
  def __init__(self,v,vocabulary):
    self.v=v
    self.vocabulary=vocabulary
  def __len__(self):
    # we want that what is len_of row in data
    return v.shape[0]
  def __getitem__(self,idx):
    question_data=v.iloc[idx]["question"]
    answer_data=v.iloc[idx]["answer"]
    question_indicess=text_to_indicess(question_data,self.vocabulary)
    answer_indicess=text_to_indicess(answer_data,self.vocabulary)
    return t.tensor(question_indicess),t.tensor(answer_indicess)

In [21]:
#make adatset and dataloader object
dataset=Ques_Ans(v,vocabulary)
dataloader=DataLoader(dataset,batch_size=1,shuffle=True)

In [22]:
dataset[0]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

In [23]:
for ques,ans in dataloader:
  print(ques,ans)

tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([[113]])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([[116]])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([[100]])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([[273]])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([[276]])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([[145]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([[205]])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([[53]])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([[49]])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([[134]])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([[225]])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([[238]])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([[215]])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84

In [24]:
import torch.nn as nn

In [25]:
#make a Architecture of RNA
class RNA(nn.Module):
  def __init__(self,data_size):
    super().__init__()
    #self.data_size=data_size
    self.embedding=nn.Embedding(data_size,embedding_dim=50)
    self.rnn=nn.RNN(50,64,batch_first=True)
    self.fc=nn.Linear(64,data_size)
  def forward(self,x_put_question):
    x=self.embedding(x_put_question)
    #RNA have  two output first hidden layer _feedback and 2nd final uotput
    hidden, x=self.rnn(x)
    x=self.fc(x.squeeze(0))
    return x



In [26]:
p=t.tensor([1,2])
p

tensor([1, 2])

In [27]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])


In [28]:
learning_rate=0.001

In [29]:
epochs=20

In [30]:
model=RNA(len(vocabulary))

In [31]:
#Entropy
loss1=nn.CrossEntropyLoss()

In [32]:
#Optimizer
optimizer=t.optim.Adam(model.parameters(),lr=learning_rate)

In [33]:
for epoch in range(epochs):
  Total_loss=0
  for ques,ans in dataloader:
    #Gradient Clear
    optimizer.zero_grad()
    #forward_pass
    y_pred=model(ques)
    #calculated loss
    Loss=loss1(y_pred,ans[0])
    #Calculated Gradient
    Loss.backward()
    #update parameters(weight and bias)
    optimizer.step()
    Total_loss+=Loss.item()
  print(f"epoch:{epoch}/{epochs},Total_loss:{Total_loss}")


epoch:0/20,Total_loss:528.4410533905029
epoch:1/20,Total_loss:457.2883677482605
epoch:2/20,Total_loss:377.7267382144928
epoch:3/20,Total_loss:317.6111361980438
epoch:4/20,Total_loss:265.6700392961502
epoch:5/20,Total_loss:216.68799209594727
epoch:6/20,Total_loss:172.49721616506577
epoch:7/20,Total_loss:134.40868240594864
epoch:8/20,Total_loss:103.85653114318848
epoch:9/20,Total_loss:79.84044057130814
epoch:10/20,Total_loss:61.50742404162884
epoch:11/20,Total_loss:48.29085171222687
epoch:12/20,Total_loss:38.8075797855854
epoch:13/20,Total_loss:31.65615762770176
epoch:14/20,Total_loss:26.035209447145462
epoch:15/20,Total_loss:21.62424162775278
epoch:16/20,Total_loss:18.141859248280525
epoch:17/20,Total_loss:15.785624168813229
epoch:18/20,Total_loss:13.554488845169544
epoch:19/20,Total_loss:11.73929838836193


In [34]:
def predict(model,question,thershold=0.5):
  question_indicess=text_to_indicess(question,vocabulary)
  question_indicess=t.tensor(question_indicess).unsqueeze(0)
  output=model(question_indicess)
  #find probability of each vector
  prob = t.nn.functional.softmax(output, dim=1)
  value,index_max_prob_value=t.max(prob,dim=1)
  if value<thershold:
    return("I don't know")
  else:
    return(list(vocabulary.keys())[index_max_prob_value])





In [35]:
predict(model,"What is the largest planet in our solar system?")

'jupiter'

In [36]:
len(vocabulary)

324

In [37]:

for i in range(len(v)):
  question=(v.iloc[i]["question"])
  print(f"question:{question}")
  predict_answer = predict(model, question)

question:What is the capital of France?
question:What is the capital of Germany?
question:Who wrote 'To Kill a Mockingbird'?
question:What is the largest planet in our solar system?
question:What is the boiling point of water in Celsius?
question:Who painted the Mona Lisa?
question:What is the square root of 64?
question:What is the chemical symbol for gold?
question:Which year did World War II end?
question:What is the longest river in the world?
question:What is the capital of Japan?
question:Who developed the theory of relativity?
question:What is the freezing point of water in Fahrenheit?
question:Which planet is known as the Red Planet?
question:Who is the author of '1984'?
question:What is the currency of the United Kingdom?
question:What is the capital of India?
question:Who discovered gravity?
question:How many continents are there on Earth?
question:Which gas do plants use for photosynthesis?
question:What is the smallest prime number?
question:Who invented the telephone?
ques

In [38]:
def question_(text):
  predict_answer = predict(model, text)
  return predict_answer



In [39]:
question_("what is capital of india")

'delhi'

In [ ]:
!pip install --upgrade gradio


In [41]:
import gradio as gr

In [43]:
gr.Interface(
    fn=question_,
    inputs="text",
    outputs=gr.Textbox(label="Answer"),
    title="G.K_(Question Answering)..For Example..What is capital of india_>Ans...Delhi",
    description="Ask a question and get the predicted answer based on the model."
).launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://be0c509afc9f500f12.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
